[options]

addons_path = /mnt/extra-addons
data_dir = /etc/odoo
admin_passwd = P4#yH6@dV9xWq2F
db_host = service_db
db_port = 5432
db_user = origo_fayzen
db_password = P4#yH6@dV9xWq2F
list_db = True
log_level = debug
logfile = /etc/odoo/odoo-server.log
workers = 0
limit_memory_hard= 2684354560
limit_memory_soft= 2147483648
limit_request = 16192888
limit_time_cpu = 60888
limit_time_real = 2240888
longpolling_port = 8072

